image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
  - ".cache/pip"
  - venv/
before_script:
- python --version
- pip install virtualenv
- virtualenv venv
- source venv/bin/activate
- pip install .[test]
- python scripts/getData.py
- python -m spacy download en_core_web_sm
test:
  script:
    - tox -e py
  artifacts:
    paths:
      - coverage.xml
    when: always
    reports:
      junit: report.xml
lint:
  script:
    - tox -e format
    - tox -e lint
coverage:
  script:
    - tox -e coverage
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - coverage.xml
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
static type check:
  script:
    - tox -e type