image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
  - ".cache/pip"
  - venv/
before_script:
- python --version
- pip install virtualenv
- virtualenv venv
- source venv/bin/activate
- pip install .
- scripts/getVolumeIndexPages
- wget https://github.com/WolfgangFahl/pyCEURmake/releases/download/v0.4.0/ceurws.db.zip -P ~/.ceurws
- unzip ~/.ceurws/ceurws.db.zip -d ~/.ceurws/
test:
  script:
    - pip install tox
    - tox -e py
