#!/bin/bash
# WF 2022-08-11
# install and test
# command to install dependencies
scripts/install "$@"
# start neo4j server
scripts/neo4j
# scripts/getVolumes
scripts/getVolumes
# command to run tests
scripts/test "$@"
