#!/bin/bash
# WF 2022-08-17
# run the wikidata proceedings query
qp=ceurws/resources/queries/ceurws.yaml
if [ ! -f /tmp/ceur.json ]
then
  sparqlquery -qp $qp -qn Proceedings -f json > /tmp/ceur.json
fi
cat /tmp/ceur.json | jq .[].sVolume | awk -v invalid="191,2284,3021" '
BEGIN {
   previous=0
   quote="\x22"
   split(invalid,invalidValues,",")
   for (invalidKey in invalidValues) {
      invalidValue=invalidValues[invalidKey]
      invalidList[invalidValue]=1
  }
}
{
  gsub(quote,"",$0)
  vol=$0
  if (vol-previous!=1) {
    firstmissing=previous+1
    if (!(firstmissing in invalidList))
      print NR,vol,previous,vol-previous,firstmissing
  }
  previous=vol
}
'
#jq . /tmp/ceur.json
