"""
CEUR-WS Wikidata community contribution analysis.

Adapted from the prototype at
https://cr.bitplan.com/index.php/CEUR-WS_Wikidata_Contributions

Computes, per Wikidata entity class:
  - number of CEUR-WS entities (instance-of class AND P179 -> Q27230297)
  - total number of entities of that class on Wikidata
  - CEUR-WS coverage percentage
  - number of community vs bot edits (creator + revision history)
  - top contributors

See: https://github.com/WolfgangFahl/pyCEURmake/issues/108

Created: 2026-05-06
@author: wf
"""

from __future__ import annotations

import dataclasses
import json
import os
import time
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

from lodstorage.query import QueryManager
from lodstorage.sparql import SPARQL

from ceurws.config import CEURWS

# Wikidata QIDs of bot accounts that mass-created CEUR-WS entries.
# Anything outside this set is treated as a community contribution.
DEFAULT_BOT_USERS: frozenset[str] = frozenset(
    {
        "CEUR-WS",        # primary CEUR-WS bot account
        "PreScholarBot",
        "DBLP-Bot",
        "KrBot",          # generic Wikidata maintenance bot
    }
)

# Default classes analysed.
# Each entry is (class_qid, label, kind) where kind is:
#   - "proceedings": item itself has wdt:P179 wd:Q27230297
#   - "event":       item is reachable as ?proc wdt:P4745 ?item from a CEUR-WS proceeding
DEFAULT_CLASSES: list[tuple[str, str, str]] = [
    ("Q1143604", "Proceedings", "proceedings"),
    ("Q2020153", "Academic conference", "event"),
    ("Q40444998", "Academic workshop", "event"),
]

WIKIDATA_ENTITY_PREFIX = "http://www.wikidata.org/entity/"


@dataclass
class HistoryRecord:
    """One QID's contributor footprint."""

    qid: str
    creator: str | None
    editors: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return dataclasses.asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "HistoryRecord":
        return cls(
            qid=d["qid"],
            creator=d.get("creator"),
            editors=list(d.get("editors", [])),
        )


@dataclass
class ContributionStats:
    """Aggregated per-class contribution statistics."""

    entity_class_qid: str
    label: str
    ceurws_count: int
    total_count: int
    coverage_pct: float
    sampled: int
    community_count: int
    bot_count: int
    top_contributors: list[tuple[str, int]]

    def to_dict(self) -> dict:
        return dataclasses.asdict(self)


class WdContributionAnalyzer:
    """
    Analyse CEUR-WS contributions to Wikidata.

    Heavy operations (history fetch over MediaWiki API) are cached on disk under
    ``~/.ceurws/wd_contributions/``.
    """

    def __init__(
        self,
        endpoint_url: str = "https://query.wikidata.org/sparql",
        bot_users: Iterable[str] | None = None,
        cache_dir: Path | None = None,
        sleep_every: int = 100,
        sleep_seconds: int = 30,
        debug: bool = False,
    ):
        """
        Args:
            endpoint_url: Wikidata SPARQL endpoint URL.
            bot_users: usernames considered bots; defaults to ``DEFAULT_BOT_USERS``.
            cache_dir: directory for JSON caches (default ``$CEURWS.CACHE_DIR/wd_contributions``).
            sleep_every: throttle the MediaWiki API every N pages.
            sleep_seconds: seconds to sleep when throttling.
            debug: verbose logging.
        """
        self.endpoint_url = endpoint_url
        self.sparql = SPARQL(endpoint_url)
        self.bot_users: set[str] = set(bot_users) if bot_users is not None else set(DEFAULT_BOT_USERS)
        self.cache_dir = cache_dir or (CEURWS.CACHE_DIR / "wd_contributions")
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        self.sleep_every = sleep_every
        self.sleep_seconds = sleep_seconds
        self.debug = debug
        self.qm = self._load_query_manager()
        self._ensure_wikidata_wikiuser()

    @staticmethod
    def _ensure_wikidata_wikiuser() -> None:
        """
        Ensure that wikibot3rd has a ``wikidata`` wikiId configured for
        anonymous read-only access (no password). Creates a minimal ini file
        on first use; existing config is left untouched.
        """
        try:
            from wikibot3rd.wikiuser import WikiUser
        except ImportError:  # pragma: no cover
            return
        ini_path = Path(WikiUser.iniFilePath("wikidata"))
        if ini_path.exists():
            return
        ini_path.parent.mkdir(parents=True, exist_ok=True)
        ini_path.write_text(
            "# auto-generated by ceurws.wd_contributions\n"
            "wikiId=wikidata\n"
            "url=https://www.wikidata.org\n"
            "scriptPath=/w/\n"
            "version=MediaWiki 1.42.0\n"
            "user=\n"
            "is_smw=False\n"
        )

    # ------------------------------------------------------------------ queries

    @staticmethod
    def _load_query_manager() -> QueryManager:
        """Load the bundled CEUR-WS named queries."""
        path = os.path.dirname(__file__)
        q_yaml = f"{path}/resources/queries/ceurws.yaml"
        return QueryManager(lang="sparql", queriesPath=q_yaml)

    def _scalar_count(self, query_name: str, class_qid: str) -> int:
        """Run a named COUNT query and return the integer result."""
        query = self.qm.queriesByName[query_name]
        sparql_str = query.query.format(class_qid=class_qid)
        rows = self.sparql.queryAsListOfDicts(sparql_str)
        if not rows:
            return 0
        return int(rows[0].get("count", 0))

    def count_ceurws(self, class_qid: str, kind: str = "proceedings") -> int:
        """Number of CEUR-WS-affiliated entities of the given class."""
        query_name = "CeurwsEventEntityCount" if kind == "event" else "CeurwsEntityCount"
        return self._scalar_count(query_name, class_qid)

    def count_total(self, class_qid: str) -> int:
        """Total number of entities of the given class on Wikidata."""
        return self._scalar_count("TotalEntityCount", class_qid)

    def list_ceurws_qids(self, class_qid: str, kind: str = "proceedings") -> list[str]:
        """Return all QIDs of CEUR-WS entities of the given class."""
        query_name = "CeurwsEventEntityList" if kind == "event" else "CeurwsEntityList"
        query = self.qm.queriesByName[query_name]
        sparql_str = query.query.format(class_qid=class_qid)
        rows = self.sparql.queryAsListOfDicts(sparql_str)
        qids: list[str] = []
        for row in rows:
            uri = row.get("item", "")
            if uri.startswith(WIKIDATA_ENTITY_PREFIX):
                qids.append(uri[len(WIKIDATA_ENTITY_PREFIX):])
        return qids

    # --------------------------------------------------------------- history

    def _cache_path(self, class_qid: str) -> Path:
        return self.cache_dir / f"history_{class_qid}.json"

    def load_cache(self, class_qid: str) -> dict[str, HistoryRecord]:
        path = self._cache_path(class_qid)
        if not path.exists():
            return {}
        try:
            with path.open("r") as fp:
                raw = json.load(fp)
        except (OSError, json.JSONDecodeError):
            return {}
        return {qid: HistoryRecord.from_dict(d) for qid, d in raw.items()}

    def save_cache(self, class_qid: str, records: dict[str, HistoryRecord]) -> None:
        path = self._cache_path(class_qid)
        with path.open("w") as fp:
            json.dump(
                {qid: r.to_dict() for qid, r in records.items()},
                fp,
                indent=2,
            )

    def fetch_history(
        self,
        qids: list[str],
        class_qid: str,
        max_items: int | None = None,
        force: bool = False,
    ) -> list[HistoryRecord]:
        """
        Fetch creator + editors for each QID; results are cached on disk.

        Args:
            qids: QIDs to query.
            class_qid: used as cache namespace.
            max_items: cap on total fetched (useful for tests).
            force: ignore cache and refetch.

        Returns:
            list of HistoryRecord, one per processed QID.
        """
        # Imported lazily so the module can be imported without the dep present
        # (e.g. when only counts are needed).
        from wikibot3rd.pagehistory import PageHistory

        cache = {} if force else self.load_cache(class_qid)
        to_fetch = [q for q in qids if q not in cache]
        if max_items is not None:
            to_fetch = to_fetch[:max_items]

        total = len(to_fetch)
        for i, qid in enumerate(to_fetch, 1):
            if self.sleep_every and i % self.sleep_every == 0:
                if self.debug:
                    print(f"[wd_contributions] throttle: sleep {self.sleep_seconds}s")
                time.sleep(self.sleep_seconds)
            try:
                ph = PageHistory(pageTitle=qid, wikiId="wikidata")
                editors = sorted({rev.user for rev in ph.revisions if rev.user})
                cache[qid] = HistoryRecord(
                    qid=qid,
                    creator=ph.getFirstUser(),
                    editors=editors,
                )
                if self.debug:
                    print(f"[wd_contributions] {i:04}/{total:04} {qid} ok")
            except Exception as e:  # pragma: no cover - network defensive
                if self.debug:
                    print(f"[wd_contributions] {i:04}/{total:04} {qid} failed: {e}")

        self.save_cache(class_qid, cache)
        # Return only records for the requested qids (in original order)
        return [cache[q] for q in qids if q in cache]

    # --------------------------------------------------------------- analysis

    def classify_contributions(
        self,
        records: list[HistoryRecord],
    ) -> tuple[int, int, Counter]:
        """
        Split records into community vs bot based on the *creator* of the item.

        Returns:
            (community_count, bot_count, Counter(creator -> count))
        """
        creators = Counter(r.creator or "<unknown>" for r in records)
        community = sum(c for u, c in creators.items() if u not in self.bot_users)
        bots = sum(c for u, c in creators.items() if u in self.bot_users)
        return community, bots, creators

    def analyze(
        self,
        classes: list[tuple[str, str, str]] | None = None,
        sample_size: int | None = None,
        force: bool = False,
    ) -> list[ContributionStats]:
        """
        Compute ContributionStats for each (class_qid, label, kind) tuple.

        Args:
            classes: list of (qid, label, kind); defaults to ``DEFAULT_CLASSES``.
                ``kind`` is "proceedings" (P179-based) or "event" (reverse P4745).
            sample_size: if set, only fetch history for this many QIDs per class
                (useful for tests; counts/coverage are still computed in full).
            force: ignore the on-disk cache.
        """
        classes = classes or DEFAULT_CLASSES
        results: list[ContributionStats] = []
        for class_qid, label, kind in classes:
            ceurws_count = self.count_ceurws(class_qid, kind=kind)
            total_count = self.count_total(class_qid)
            coverage = (100.0 * ceurws_count / total_count) if total_count else 0.0

            qids = self.list_ceurws_qids(class_qid, kind=kind)
            records = self.fetch_history(
                qids, class_qid=class_qid, max_items=sample_size, force=force
            )
            community, bots, creators = self.classify_contributions(records)
            top = creators.most_common(5)

            results.append(
                ContributionStats(
                    entity_class_qid=class_qid,
                    label=label,
                    ceurws_count=ceurws_count,
                    total_count=total_count,
                    coverage_pct=round(coverage, 3),
                    sampled=len(records),
                    community_count=community,
                    bot_count=bots,
                    top_contributors=top,
                )
            )
        return results

    # --------------------------------------------------------------- rendering

    @staticmethod
    def as_markdown_table(stats: list[ContributionStats]) -> str:
        header = (
            "| Class | QID | CEUR-WS | Total | Coverage % "
            "| Sampled | Community | Bot | Top contributors |\n"
            "|---|---|---:|---:|---:|---:|---:|---:|---|\n"
        )
        rows = []
        for s in stats:
            top = ", ".join(f"{u} ({c})" for u, c in s.top_contributors)
            rows.append(
                f"| {s.label} | {s.entity_class_qid} | {s.ceurws_count} | {s.total_count} "
                f"| {s.coverage_pct:.2f} | {s.sampled} | {s.community_count} | {s.bot_count} "
                f"| {top} |"
            )
        return header + "\n".join(rows) + "\n"

    @staticmethod
    def as_latex_table(stats: list[ContributionStats]) -> str:
        lines = [
            r"\begin{tabular}{lrrrrrrl}",
            r"\hline",
            r"Class & CEUR-WS & Total & Cov.\,\% & Sampled & Community & Bot & Top \\",
            r"\hline",
        ]
        for s in stats:
            top = ", ".join(f"{u} ({c})" for u, c in s.top_contributors)
            # escape underscores in usernames for LaTeX
            top_escaped = top.replace("_", r"\_")
            label_escaped = s.label.replace("_", r"\_")
            lines.append(
                f"{label_escaped} & {s.ceurws_count} & {s.total_count} "
                f"& {s.coverage_pct:.2f} & {s.sampled} & {s.community_count} "
                f"& {s.bot_count} & {top_escaped} \\\\"
            )
        lines += [r"\hline", r"\end{tabular}"]
        return "\n".join(lines) + "\n"

    @staticmethod
    def as_json(stats: list[ContributionStats]) -> str:
        return json.dumps([s.to_dict() for s in stats], indent=2)
