# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GHACTIONS: ACTIVE

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.10', '3.11', '3.12' ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: start neo4j
      run: |
        scripts/neo4j

    - name: install
      run: |
        scripts/install

    - name: Cache Sqlite
      id: cache-sqlite
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.ceurws
        key: ceurws

    - name: fill sqlite
      if: steps.cache-sqlite.outputs.cache-hit != 'true'
      run: |
        python scripts/getData.py
    - name: save Sqlite
      id: saveSqlite
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/.ceurws
        key: ceurws

    - name: Run tests
      # Run tox using the version of Python in `PATH`
      run: scripts/test

    - name: Run Ruff
      run: ruff check --output-format=github .
