# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GHACTIONS: ACTIVE

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        #python-version: [3.8, 3.9, '3.10','3.11']
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: install
      run: |
        scripts/install
#       pip install sphinx
#       pip install sphinx_rtd_theme
#       scripts/doc

    - name: Cache Sqlite
      id: cache-sqlite
      uses: actions/cache@v3
      with:
        path: ~/.ceurws
        key: ceurws

    - name: fill sqlite
      if: steps.cache-sqlite.outputs.cache-hit != 'true'
      run: |
        ceur-ws --recreate

    - name: save Sqlite
      id: saveSqlite
      uses: actions/cache/save@v3
      with:
        path: ~/.ceurws
        key: ceurws

    - name: start neo4j
      run: |
        scripts/neo4j

    - name: Run tests
      run: |
        scripts/getVolumes
        scripts/test
